---
kubeconfig_admin: "/etc/kubernetes/admin.conf"
addons_directoy: "/etc/kubernetes/addons"

cni: "cilium"

calico:
  version: "3.7.3"

cilium:
  version: "latest"
  debug: "false"
  prepend_iptables_chains: "false"
  enable_ipv4: "true"
  enable_ipv6: "false"
  wait_bpf_mount: "true"
  kube_proxy_replacement: "strict"
  enable_node_port: "true"
  enable_host_port: "false"
