---
kubeconfig_admin: "/etc/kubernetes/admin.conf"
addons_directoy: "/etc/kubernetes/addons"

psp:
  default: "relaxed"

cni: "cilium"
#cni: "calico"

flannel:
  version: "v0.12.0-amd64"
  cni_conf_name: "10-flannel.conflist"

calico:
  version: "v3.16.1"
  cni_conf_name: "10-calico.conflist"
  ip_autodetection_method: "interface=.*"
  ip6_autodetection_method: "interface=.*"
  mtu: "1420"

cilium:
  version: "v1.8.5"
  cni_conf_name: "05-cilium.conf"
  mtu: "1420"
  debug: "false"
  prepend_iptables_chains: "true"
  enable_ipv4: "true"
  ipv4_mask_size: "24"
  enable_ipv6: "false"
  wait_bpf_mount: "true"
  kube_proxy_replacement: "strict"
  enable_external_ips: "false"
  enable_host_reachable_services: "true"
  enable_node_port: "true"
  enable_health_check_nodeport: "true"
  enable_host_port: "false"
