---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp.kube-proxy
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'runtime/default'
    apparmor.security.beta.kubernetes.io/allowedProfileName: '*'
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
   - NET_ADMIN
   - SYS_MODULE
  volumes:
    - configMap
    - secret
    - hostPath
  allowedHostPaths:
    - pathPrefix: /lib/modules
    - pathPrefix: /run/xtables.lock
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:kube-proxy
rules:
  - apiGroups: ['extensions']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames: ['psp.kube-proxy']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp:kube-proxy
roleRef:
  kind: ClusterRole
  name: psp:kube-proxy
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kube-proxy
  namespace: kube-system
