---
kubeconfig:
  local_path: "{{ inventory_dir }}/secrets/kubernetes/admin.conf"

psp:
  default: "relaxed"

cni:
  name: "cilium"
  # mtu: "1440"
  # ipv4_mask_size: "24"
  # enable_ipv4: "true"
  # enable_ipv6: "false"

calico:
  # version: "v3.16.1"
  # backend: "vxlan"
  cni_conf_name: "10-calico.conflist"
  # ip_autodetection_method: "interface=.*"
  # ip6_autodetection_method: "interface=.*"

  # ippool:
  #   ipip_mode: "Never"
  #   nat_outgoing: "true"
  #   vxlan_mode: "Always"

  # felix:
  #   bpf_enabled: "true"
  #   bpf_external_service_mode: "Tunnel" # || DSR
  #   bpf_log_level: "Info"
  #   log_severity_screen: "Info"

cilium:
  # version: "v1.8.5"
  cni_conf_name: "05-cilium.conflist"
  # debug: "false"
  # prepend_iptables_chains: "true"
  # wait_bpf_mount: "true"
  # kube_proxy_replacement: "strict"
  # enable_external_ips: "false"
  # enable_host_reachable_services: "true"
  # enable_node_port: "true"
  # enable_health_check_nodeport: "true"
  # enable_host_port: "false"

flannel:
  version: "v0.12.0-amd64"
  cni_conf_name: "10-flannel.conflist"
