---
crio_repo_base: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_"

crio_version: 1.17.0
crio_pkgs:
  - name: cri-o-1.16.0
    state: absent
  - name: cri-o-1.17.0
    state: present

runtime_endpoint: "/run/crio/crio.sock"
image_endpoint: "/run/crio/crio.sock"
cgroup_manager: "systemd"

crictl:
  debug: "false"
  timeout: "8"
