image:
  registry: r.spiarh.fr
  name: k9s
  tag: 0.24.9
spec:
  fromImages:
  - registry: docker.io/library
    name: golang
    tag: "1.16-alpine"
    target: builder
  - registry: r.spiarh.fr
    name: alpine
    tag: 3.13.2
  buildArgs:
  - K9S_VERSION
  - KUBECTL_VERSION
  tagFormat: '{{ .K9S_VERSION }}'
  facts:
  - name: K9S_VERSION
    value: 0.24.9
    source: k9s
    kind: version
  - name: KUBECTL_VERSION
    value: 1.21.0
    kind: version
  sources:
  - name: k9s
    github:
      owner: derailed
      repository: k9s
      object: release
