---
host_vars_dir: "{{ inventory_dir }}/host_vars"

secrets:
  dir: "{{ inventory_dir }}/secrets"
  wireguard: true
  kubernetes: true
  vault_encrypt: true

wireguard:
  dir: "{{ inventory_dir }}/secrets/wireguard"
  secrets_dir: "{{ inventory_dir }}/secrets/wireguard/{{ inventory_hostname }}"
