---
host_vars_dir: "{{ inventory_dir }}/host_vars"

secrets:
  dir: "{{ inventory_dir }}/secrets"
  wireguard: true
  kubernetes: true
  vault_encrypt: true

wireguard:
  dir: "{{ inventory_dir }}/secrets/wireguard"
  secrets_dir: "{{ inventory_dir }}/secrets/wireguard/{{ inventory_hostname }}"

kubernetes:
  secrets_dir: "{{ inventory_dir }}/secrets"
  # KUBEADM
  kubeadm:
    dir: "{{ inventory_dir }}/secrets/kubernetes/kubeadm"
    token: "{{ inventory_dir }}/secrets/kubernetes/kubeadm/token"
    ca_cert_hash: "{{ inventory_dir }}/secrets/kubernetes/kubeadm/ca-cert-hash"
  # KUBERNETES
  pki:
    dir: "{{ inventory_dir }}/secrets/kubernetes/pki"
    etcd_dir: "{{ inventory_dir }}/secrets/kubernetes/pki/etcd"
    sa:
      key: "{{ inventory_dir }}/secrets/kubernetes/pki/sa.key"
      pub: "{{ inventory_dir }}/secrets/kubernetes/pki/sa.pub"
    ca:
      common_name: "{{ (cluster_name | default('kubernetes')) + '-ca' }}"
      openssl_conf: "{{ inventory_dir }}/secrets/kubernetes/pki/ca_openssl.conf"
      crt: "{{ inventory_dir }}/secrets/kubernetes/pki/ca.crt"
      key: "{{ inventory_dir }}/secrets/kubernetes/pki/ca.key"
    front_proxy_ca:
      common_name: "front-proxy-ca"
      openssl_conf: "{{ inventory_dir }}/secrets/kubernetes/pki/front-proxy_openssl.conf"
      crt: "{{ inventory_dir }}/secrets/kubernetes/pki/front-proxy-ca.crt"
      key: "{{ inventory_dir }}/secrets/kubernetes/pki/front-proxy-ca.key"
    etcd:
      common_name: "etcd-ca"
      openssl_conf: "{{ inventory_dir }}/secrets/kubernetes/pki/etcd/ca_openssl.conf"
      crt: "{{ inventory_dir }}/secrets/kubernetes/pki/etcd/ca.crt"
      key: "{{ inventory_dir }}/secrets/kubernetes/pki/etcd/ca.key"
