---
# defaults file for users
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDvBiyxnCaL3zU8VUDdFyrCdU9HgRzzD5Jp76bhwsulMDAd0CbmX+RIwRTL+IkEK7y6OmEMmBY8zKpwwoE70CFtUHLKjKlsJGu6miw3IQx7rJ+Bn0AbUxoq5ho/ovysiKNZjn4cUH/XbKQENfX1LVjnh2fBNfgMvGaOJ5pPxu+Ky5mWkFXCONOQRvYeQ/gSMeKOJAuYUx/Tf1svrm14+HUr3evNbYlGOwbK5bNhS54EX1ZodA7RrOrPSJjIsLoRPm6bre5VxovHc4q8AMgTJ5KM7VnuQqKLbMQZBJGCu01W/hXAjM7JC/gz3ahEHeDEVDoVq9k3qywMEpaEkfNNKd6e9TCqBSTtjjtkD2MEmkXXQsupStPSh+pny/tu+4J2ITyoqh8H+bgSPCH/nGjsGF3wKFyKoNgeztQmqkHxIdqVeIjNnIavNuH9vuURJbTl7Igckd1Jja02xA5bo1q4zoyPcd5P8Fz6sdmiFYV2sg1SUw9gl9N1KCXYmOwLVRq+OQBaeWn6TymA56gZ1c6co0RDFGzaI7XQYRYydyQt7fPshkQXonOmWTqtNvOON4QGGWX2Qso/9Xe8RGlGTMPeCghGICYlUWicahRUqp3zkqUQIT0JLuVgUduHmM8g24URqbHDM1nOfJfRG0PWLEzcdYzkltfbVj8w9trVHXd7DaV1nw== /home/lcavajani/.ssh/id_rsa
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHUkbmn1u0EPaf1Nqnx8KSn9sfcgLxsaDSyPy+xmHJ1 lcavajani


os_groups:
  thack:
    gid: 1111

os_users:
  root:
    uid: 0
    group: root
    shell: /bin/bash
    home: /root
    sudo: true
  thack:
    uid: 1111
    group: thack
    shell: /bin/bash
    home: /home/thack
    sudo: true
