---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: kube-state-metrics
  app.kubernetes.io/managed-by: kustomize

# images:
# - name: kube-state-metrics
#   newName: quay.io/coreos/kube-state-metrics
#   newTag: "v1.9.7"

resources:
- ./clusterrolebinding.yaml
- ./clusterrole.yaml
- ./deployment.yaml
- ./podsecuritypolicy.yaml
- ./serviceaccount.yaml
- ./service.yaml
