---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana
subjects:
- kind: ServiceAccount
  name: grafana
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana:psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana:psp
subjects:
- kind: ServiceAccount
  name: grafana
  namespace: default
