apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: node-exporter
  app.kubernetes.io/name: prometheus
  app.kubernetes.io/managed-by: kustomize

images:
- name: prometheus-node-exporter
  newName: prom/node-exporter
  newTag: v1.0.1

resources:
- ./daemonset.yaml
- ./podsecuritypolicy.yaml
- ./rolebinding.yaml
- ./role.yaml
- ./serviceaccount.yaml
- ./service.yaml
