from_image:
  name: alpine
  registry: r.spiarh.fr
  tag: 3.12.1
from_image_builder: null
image:
  name: tblshoot
  registry: r.spiarh.fr
  tag: latest
  tag_build:
    type: VERSION
    version: null
    version_from: null
