---
- name: install_unattended_upgrades
  apt:
    name: unattended-upgrades
    state: latest

- name: configure_unattended_upgrades
  template:
    src: 51unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/51unattended-upgrades
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_unattended_upgrades

- name: configure_unattended_upgrades_auto
  template:
    src: 21auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/21auto-upgrades
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_unattended_upgrades

- name: start_enable_service_unattended_upgrades
  service:
    name: unattended-upgrades.service
    state: started
    enabled: True
