---
- name: create_dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - "{{ host_vars_dir }}"
    - "{{ secrets_vars_dir }}"
  delegate_to: localhost
  run_once: true

- import_tasks: wireguard.yml
  delegate_to: localhost

- import_tasks: kubernetes.yml
  delegate_to: localhost
  run_once: true
