- name: check_if_secrets_encrypted
  lineinfile:
    path: "{{ item.path }}"
    regexp: '^\$ANSIBLE_VAULT.*AES256$'
    state: absent
  check_mode: yes
  changed_when:
    - secrets_encrypted.found == 0
  with_items: "{{ all_secrets_to_encrypt.files }}"
  register: secrets_encrypted

# set back to writeable before encrypt if it was set to RO before
- name: change_secrets_perm_before_encrypt
  file:
    path: "{{ item.item.path }}"
    mode: 0600
  with_items: "{{ secrets_encrypted.results }}"
  when: item.changed == true

- name: encrypt_secrets
  shell: ansible-vault encrypt "{{ item.item.path }}"
  with_items: "{{ secrets_encrypted.results }}"
  when: item.changed == true
