- name: set_wireguard_secrets_path
  set_fact:
    wg_secrets: >-
      {%- set data = {} -%}
      {%- for wg in wireguard.interfaces -%}
      {%- do data.update({wg: {
            'priv_key': ([wireguard.secrets_dir, wg, 'priv_key'] | join("/")),
            'pub_key': ([wireguard.secrets_dir, wg, 'pub_key'] | join("/")),
            'preshared_key': ([wireguard.secrets_dir, wg, 'preshared_key'] | join("/"))
          }
        })
      -%}
      {%- endfor -%}
      {{ data }}

- name: create_wireguard_secrets_dir
  file:
    path: "{{ wireguard.secrets_dir + '/' + item }}"
    state: directory
    mode: 0700
  delegate_to: localhost
  with_items:
    - "{{ wireguard.interfaces }}"

###############      
# PRIVATE KEY #
###############
- name: check_wireguard_priv_key_exists
  stat:
    path: "{{ item.value.priv_key }}"
  register: priv_key
  with_dict:
    - "{{ wg_secrets }}"

- name: create_wireguard_priv_key
  shell: wg genkey > "{{ item.item.value.priv_key }}"
  when:
  - item.stat.exists == false
  with_items:
    - "{{ priv_key.results }}"

- name: check_wireguard_priv_key_exists
  stat:
    path: "{{ item.value.priv_key }}"
  register: priv_key
  with_dict:
    - "{{ wg_secrets }}"

##############
# PUBLIC KEY #
##############
- name: check_wireguard_pub_key_exists
  stat:
    path: "{{ item.value.pub_key }}"
  register: pub_key
  with_dict:
    - "{{ wg_secrets }}"

- name: create_wireguard_pub_key
  shell: wg pubkey < "{{ item.item.value.priv_key }}" > "{{ item.item.value.pub_key }}"
  when:
  - item.stat.exists == false
  with_items:
    - "{{ pub_key.results }}"

#################
# PRESHARED KEY #
#################
- name: check_wireguard_preshared_key_exists
  stat:
    path: "{{ item.value.preshared_key }}"
  register: preshared_key
  with_dict:
    - "{{ wg_secrets }}"

- name: create_wireguard_preshared_key
  shell: wg genpsk > "{{ item.item.value.preshared_key }}"
  when:
  - item.stat.exists == false
  with_items:
    - "{{ preshared_key.results }}"
