- name: create_wireguard_secrets_dir
  file:
    path: "{{ wireguard.secrets_dir }}"
    state: directory
    mode: 0700
  delegate_to: localhost

###############      
# PRIVATE KEY #
###############
- name: check_wireguard_priv_key_exists
  stat:
    path: "{{ wireguard.priv_key }}"
  register: priv_key

- name: create_wireguard_priv_key
  shell: wg genkey > "{{ wireguard.priv_key }}"
  when:
  - priv_key.stat.exists == false

- name: check_wireguard_priv_key_exists
  stat:
    path: "{{ wireguard.priv_key }}"
  register: priv_key

- name: change_priv_key_perm
  file:
    path: "{{ wireguard.priv_key }}"
    mode: '0400'
  when:
  - priv_key.stat.exists == true

##############
# PUBLIC KEY #
##############
- name: check_wireguard_pub_key_exists
  stat:
    path: "{{ wireguard.pub_key }}"
  register: pub_key

- name: create_wireguard_pub_key
  shell: wg pubkey < "{{ wireguard.priv_key }}" > "{{ wireguard.pub_key }}"
  when:
  - priv_key.stat.exists == true
  - pub_key.stat.exists == false

- name: check_wireguard_pub_key_exists
  stat:
    path: "{{ wireguard.pub_key }}"
  register: pub_key

- name: change_pub_key_perm
  file:
    path: "{{ wireguard.pub_key }}"
    mode: '0400'
  when:
  - pub_key.stat.exists == true

#################
# PRESHARED KEY #
#################
- name: check_wireguard_preshared_key_exists
  stat:
    path: "{{ wireguard.preshared_key }}"
  register: preshared_key

- name: create_wireguard_preshared_key
  shell: wg genpsk > "{{ wireguard.preshared_key }}"
  when:
  - preshared_key.stat.exists == false

- name: check_wireguard_preshared_key_exists
  stat:
    path: "{{ wireguard.preshared_key }}"
  register: preshared_key

- name: change_wireguard_preshared_key_perm
  file:
    path: "{{ wireguard.preshared_key }}"
    mode: '0400'
  when:
  - preshared_key.stat.exists == true
