---
packages_to_remove:
  - openvswitch
  - thunderbird-enigmail

packages_from_default_repos:
  - akmod-nvidia
  - ansible
  - acpid
  - awscli
  - bat
  - bcc
  - buildah
  - chromium
  - curl
  - cmake
  - deja-dup
  - dkms
  - faketime
  - ffmpeg
  - filezilla
  - ftp
  - freerdp
  - fwupd
  - fzf
  - gcc
  - gcc-c++
  - gcc-gdb-plugin
  - google-cloud-sdk
  - gimp
  - git
  - gnome-tweaks
  - gnome-shell-theme-yaru
  - golang
  - golang-x-tools-benchcmp
  - golang-x-tools-bundle
  - golang-x-tools-callgraph
  - golang-x-tools-compilebench
  - golang-x-tools-cover
  - golang-x-tools-devel
  - golang-x-tools-digraph
  - golang-x-tools-eg
  - golang-x-tools-fiximports
  - golang-x-tools-getgo
  - golang-x-tools-go-contrib-init
  - golang-x-tools-godex
  - golang-x-tools-goimports
  - golang-x-tools-gomvpkg
  - golang-x-tools-gopls
  - golang-x-tools-gorename
  - golang-x-tools-goyacc
  - golang-x-tools-guru
  - golang-x-tools-present
  - golang-x-tools-splitdwarf
  - golang-x-tools-ssadump
  - golang-x-tools-stress
  - golang-x-tools-stringer
  - golang-x-tools-toolstash
  - grubby
  - htop
  - httrack
  - iftop
  - ipcalc
  - iperf3
  - ipmitool
  - jq
  - lshw
  - libglvnd-glx
  - libglvnd-opengl
  - libglvnd-devel
  - minicom
  - mlocate
  - mtr
  - mumble
  - nmap
  - nmap-ncat
  #- nodejs
  - openvpn
  - openssh-askpass
  - picocom
  - podman
  - pkgconfig
  - pylint
  - python3-autopep8
  - python3-devel
  - python3-flake8
  - python3-netaddr
  - python3-pip
  - python3-pytest
  - python3-virtualenv
  - python3-virtualenvwrapper
  - pssh
  - qemu-audio-alsa
  - qemu-audio-oss
  - qemu-audio-pa
  - qemu-audio-sdl
  - qemu-block-curl
  - qemu-block-dmg
  - qemu-block-gluster
  - qemu-block-iscsi
  - qemu-block-nfs
  - qemu-block-rbd
  - qemu-block-ssh
  - qemu-common
  - qemu-guest-agent
  - qemu-img
  - qemu-kvm
  - qemu-system-x86
  - qemu-system-x86-core
  - qemu-ui-curses
  - qemu-ui-gtk
  - qemu-ui-sdl
  - qemu-ui-spice-app
  - kernel-devel
  - kernel-headers
  - kernel-tools
  - libguestfs-tools
  - libvirt-client
  - libvirt-daemon
  - libvirt-daemon-driver-interface
  - libvirt-daemon-driver-network
  - libvirt-daemon-driver-nodedev
  - libvirt-daemon-driver-nwfilter
  - libvirt-daemon-driver-qemu
  - libvirt-daemon-driver-secret
  - libvirt-daemon-driver-storage
  - libvirt-daemon-driver-storage-core
  - libvirt-daemon-driver-storage-disk
  - libvirt-daemon-driver-storage-gluster
  - libvirt-daemon-driver-storage-iscsi
  - libvirt-daemon-driver-storage-iscsi-direct
  - libvirt-daemon-driver-storage-logical
  - libvirt-daemon-driver-storage-mpath
  - libvirt-daemon-driver-storage-rbd
  - libvirt-daemon-driver-storage-scsi
  - libvirt-daemon-driver-storage-sheepdog
  - libvirt-daemon-driver-storage-zfs
  - libvirt-daemon-kvm
  - pass
  - rdesktop
  - ruby
  - ruby-devel
  - rhythmbox
  - salt-master
  - salt-ssh
  - screen
  - skopeo
  - ShellCheck
  - shutter
  - sshuttle
  - strace
  - sysstat
  - tcpdump
  - terminator
  - transmission
  - tree
  - yamllint
  - yarnpkg
  - youtube-dl
  - vim
  - vim-X11
  - vlc
  - virt-install
  - virt-manager
  - wireguard-tools
  - wireshark

packages_from_external_repos:
  - brave-browser-beta
  - code
  - kubectl
  - terraform

#rpm_keys_to_remove:

#rpm_keys_to_add:
#  - https://packages.microsoft.com/keys/microsoft.asc
#  - https://brave-browser-rpm-beta.s3.brave.com/brave-core-nightly.asc

yum_repo_to_del:
  - fedora-cisco-openh264

yum_repo_to_add:
  - name: brave
    description: "Brave browser repository"
    file: brave.repo
    baseurl: https://brave-browser-rpm-beta.s3.brave.com/x86_64/
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: 1
    gpgkey: https://brave-browser-rpm-beta.s3.brave.com/brave-core-nightly.asc
  - name: vscode
    description: "Visual Studio Code"
    file: vscode.repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: 1
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  - name: kubernetes
    description: "Kubernetes repository"
    file: kubernetes.repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: 1
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  - name: hashicorp
    description: "Hashicorp"
    file: hashicorp.repo
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: 1
    gpgkey: https://rpm.releases.hashicorp.com/gpg
  - name: hashicorp-test
    description: "Hashicorp Test"
    file: hashicorp-test.repo
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/test
    enabled: no
    gpgcheck: yes
    repo_gpgcheck: 1
    gpgkey: https://rpm.releases.hashicorp.com/gpg
  - name: google-cloud-sdk
    description: "Google Cloud SDK"
    file: google-cloud-sdk.repo
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: 1
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

services_to_disable:
  - bluetooth.service
  - iscsi.service
  - iscsid.socket
  - iscsiuio.socket
  - multipathd.socket
  - multipathd.service
  - ModemManager.service
  - sssd.service
  - sssd-kcm.service
  - sssd-kcm.socket


services_to_enable:
  - libvirtd

sudo:
  timeout: 30

#scat
#password-store
#iozone
#lxd
#python3-flake8
#python3-neutronclient
#python3-openstackclient
#python3-yamllint
#unrar
#rar
#libcap-progs
#glibc-devel-static
#go-doc
#cf-cli
#terraform-provider-susepubliccloud

#
#
#
#yum_repos_to_add:
#
