---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: loki
  app.kubernetes.io/managed-by: kustomize

# images:
# - name: loki
#   newName: docker.io/grafana/loki
#   newTag: "2.2.0"

configMapGenerator:
- name: loki
  behavior: create
  files:
  - ./config/loki.yaml

resources:
- ./podsecuritypolicy.yaml
- ./rolebinding.yaml
- ./role.yaml
- ./serviceaccount.yaml
- ./service-headless.yaml
- ./service.yaml
- ./statefulset.yaml
