---
- name: check_podcidr
  command: "kubectl get nodes {{ ansible_nodename }} -ojsonpath='{.spec.podCIDR}'"
  delegate_to: localhost
  changed_when: false
  register: node_podcidr

- name: add_podcdir
  command: "kubectl patch node {{ ansible_nodename }} -p '{\"spec\":{\"podCIDR\":\"{{ pod_cidr }}\"}}'"
  delegate_to: localhost
  when:
    - kubernetes.controller_manager.allocate_node_cidrs == "false"
    - pod_cidr not in node_podcidr.stdout
