---
- name: check_noschedule_taint
  command: "kubectl get nodes {{ ansible_nodename }} -ojsonpath='{.spec.taints}'"
  delegate_to: localhost
  changed_when: false
  register: node_taints

- name: add_noschedule_taint
  command: "kubectl taint node {{ ansible_nodename }} node-role.kubernetes.io/master=:NoSchedule"
  delegate_to: localhost
  when:
    - taints.master.noschedule
    - '"NoSchedule" not in node_taints.stdout'
    - inventory_hostname in groups['masters']

- name: remove_noschedule_taint
  command: "kubectl taint node {{ ansible_nodename }} node-role.kubernetes.io/master=:NoSchedule-"
  delegate_to: localhost
  when:
    - taints.master.noschedule == false
    - '"NoSchedule" in node_taints.stdout'
    - inventory_hostname in groups['masters']
