image:
  registry: r.spiarh.fr
  name: gopass
  tag: 1.12.6
spec:
  fromImages:
  - registry: docker.io/library
    name: golang
    tag: 1.16-alpine
    target: builder
  - registry: r.spiarh.fr
    name: alpine
    tag: 3.12.1
  buildArgs:
  - VERSION
  tagFormat: '{{ .VERSION }}'
  facts:
  - name: VERSION
    value: 1.12.6
    source: github
    kind: version
  sources:
  - name: github
    github:
      owner: gopasspw
      repository: gopass
      object: release
