---
apiserver_listen_interface: ""
kubelet_listen_interface: ""
#kubelet_kubeadm_args: "--container-runtime=remote --container-runtime-endpoint=/var/run/crio/crio.sock --resolv-conf=/run/systemd/resolve/resolv.conf"
kubelet_kubeadm_args: ""

admission_plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,PersistentVolumeClaimResize,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,NodeRestriction,PodSecurityPolicy"
cluster_name: "the_knick"
control_plane_endpoint: "services.maison.lan:6443"
kubernetes_version: "1.17.2"

pod_subnet_cidr: "172.16.0.0/16"
service_subnet: "172.17.0.0/16"

kubeadm_init_file: "/etc/kubernetes/kubeadm-init.yaml"
kubeadm_join_file: "/etc/kubernetes/kubeadm-join.yaml"
init_witness_file: "/etc/kubernetes/init_already_done"
join_witness_file: "/etc/kubernetes/join_already_done"

#kubeconfig_admin: "/etc/kubernetes/admin.conf"

kubelet_extra_configuration_default: |
  cgroupDriver: systemd
  cgroupRoot: /
  kubeletCgroups: /podruntime.slice
  kubeReservedCgroup: /podruntime.slice
  resolvConf: /run/systemd/resolve/resolv.conf
  runtimeCgroups: /podruntime.slice
  systemReserved:
    cpu: 250m
    memory: 256Mi
  resolvConf: /run/systemd/resolve/resolv.conf

kubelet_extra_configuration_kubereserved: |
  kubeReserved:
    cpu: 250m
    memory: 256Mi
    ephemeral-storage: 1024Mi

# /etc/default/kubelet 
kubelet_extra_args: ""

# Split with comma "phase1,phase2"
init_skip_phases: "addon/kube-proxy"
join_skip_phases: ""

cert_path: "pki"
token: "{{lookup('file', 'templates/kubeadm/token')}}"

# openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
ca_cert_hash: "{{lookup('file', 'templates/kubeadm/ca_cert_hash')}}"

reset:
  clean_iptables: false
