---
kubeconfig:
  remote_path: "/etc/kubernetes/admin.conf"
  local_path: "{{ inventory_dir }}/secrets/kubernetes/admin.conf"

cert_path: "{{ inventory_dir }}/secrets/kubernetes/pki"

kubernetes:
  apiserver:
    admission_plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,PersistentVolumeClaimResize,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,NodeRestriction,PodSecurityPolicy"
    listen_interface: ""

  controller_manager:
    listen_interface: ""

  scheduler:
    listen_interface: ""

  cluster_name: "the_knick"
  control_plane_endpoint: "services.maison.lan:6443"
  version: "1.19.2"

pod_subnet_cidr: "172.16.0.0/16"
service_subnet_cidr: "172.17.0.0/16"

etcd:
  data_dir: "/var/lib/etcd"

kubeadm:
  # openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
  ca_cert_hash: "{{lookup('file', inventory_dir + '/secrets/kubernetes/kubeadm/ca-cert-hash')}}"
  init:
    # Split with comma "addon/kube-proxy"
    skip_phases: ""
    config_file: "/etc/kubernetes/kubeadm-init.yaml"
    witness_file: "/etc/kubernetes/init_already_done"
  join:
    skip_phases: ""
    config_file: "/etc/kubernetes/kubeadm-join.yaml"
    witness_file: "/etc/kubernetes/join_already_done"
  # "--container-runtime=remote --container-runtime-endpoint=/var/run/crio/crio.sock --resolv-conf=/run/systemd/resolve/resolv.conf"
  kubelet_args: ""
  log_level: "5"
  token: "{{lookup('file', inventory_dir + '/secrets/kubernetes/kubeadm/token')}}"

kubelet:
  # /etc/default/kubelet
  extra_args: ""
  extra_configuration_default: |
    cgroupDriver: systemd
    cgroupRoot: /
    kubeletCgroups: /podruntime.slice
    kubeReservedCgroup: /podruntime.slice
    runtimeCgroups: /podruntime.slice
    resolvConf: /run/systemd/resolve/resolv.conf
    systemReserved:
      cpu: 100m
      memory: 128Mi
  extra_configuration_kubereserved: |
    kubeReserved:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 1024Mi
  listen_interface: ""

kube_proxy:
  mode: ""
  nodeport_addresses:
    cidr: []
    interfaces: []
  # extra_configuration_default: |
  extra_configuration_default: ""

reset:
  clean_iptables: false
