---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: hugo
  app.kubernetes.io/name: hugo
  app.kubernetes.io/managed-by: kustomize

resources:
- deployment.yaml
- serviceaccount.yaml
- service.yaml
