---
# defaults file for ssh
sshd_default_config:
  Port: 2889
  ListenAddress: 0.0.0.0
  Protocol: 2
  KexAlgorithms: "curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256"
  Ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
  MACs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"
  # Logging
  SyslogFacility: AUTH
  LogLevel: INFO
  # Authentication:
  LoginGraceTime: 120
  PermitRootLogin: "no"
  StrictModes: "yes"
  PubkeyAuthentication: "yes"
  HostbasedAuthentication: "no"
  PermitEmptyPasswords: "no"
  # Change to yes to enable challenge-response passwords (beware issues with
  # some PAM modules and threads)
  ChallengeResponseAuthentication: "no"
  # Change to no to disable tunnelled clear text passwords
  PasswordAuthentication: "no"
  X11Forwarding: "no"
  X11DisplayOffset: 10
  PrintMotd: "no"
  PrintLastLog: "yes"
  TCPKeepAlive: "yes"
  Banner: /etc/issue.net
  AcceptEnv: "LANG LC_*"
  Subsystem: "sftp /usr/lib/openssh/sftp-server"
  # Set this to 'yes' to enable PAM authentication, account processing,
  # and session processing. If this is enabled, PAM authentication will
  # be allowed through the ChallengeResponseAuthentication and
  # PasswordAuthentication.  Depending on your PAM configuration,
  # PAM authentication via ChallengeResponseAuthentication may bypass
  # the setting of "PermitRootLogin without-password".
  # If you just want the PAM account and session checks to run without
  # PAM authentication, then enable this but set PasswordAuthentication
  # and ChallengeResponseAuthentication to 'no'.
  UsePAM: "yes"

# HostKeys for protocol version 2
sshd_host_keys:
  - /etc/ssh/ssh_host_rsa_key
  - /etc/ssh/ssh_host_ed25519_key

#sshd_extra_config:

sshd_allowed_users:
  - thack
