---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: server
  app.kubernetes.io/name: prometheus
  app.kubernetes.io/managed-by: kustomize

images:
- name: prometheus-server-configmap-reload
  newName: docker.io/jimmidyson/configmap-reload
  newTag: "v0.4.0"
- name: prometheus-alertmanager
  newName: docker.io/prom/alertmanager
  newTag: "v0.21.0"

configMapGenerator:
- name: prometheus-alertmanager
  files:
  - ./config/alertmanager.yml

resources:
- ./clusterrolebinding.yaml
- ./clusterrole.yaml
- ./podsecuritypolicy.yaml
- ./serviceaccount.yaml
- ./service-headless.yaml
- ./service.yaml
- ./statefulset.yaml
