---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-alertmanager
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9093
  sessionAffinity: None
  type: ClusterIP
