---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: goldpinger
  app.kubernetes.io/managed-by: kustomize

resources:
- rolebinding.yaml
- role.yaml
- daemonset.yaml
- serviceaccount.yaml
- service.yaml
