---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: goldpinger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: goldpinger
subjects:
  - kind: ServiceAccount
    name: goldpinger
