---
- name: stop_enable_services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: False
  with_items:
    - "{{ services_to_disable | default([]) }}"

- name: start_enable_services
  service:
    name: "{{ item }}"
    state: started
    enabled: True
  with_items:
    - "{{ services_to_enable | default([]) }}"
