---
- name: deploy_masters
  hosts: masters
  gather_facts: true
  serial: 1
  roles:
    - kubernetes-kubeadm

- hosts: masters
  connection: local
  vars:
    ansible_become: False
  tasks:
    - include_role:
        name: kubernetes-kubeadm
        tasks_from: admin-conf/encrypt-local.yml

- name: deploy_workers
  hosts: workers
  gather_facts: true
  roles:
    - kubernetes-kubeadm
