- name: kubernetes-upgrade
  gather_facts: true
  hosts:
  - masters
  - workers
  serial: 1
  roles:
    - kubernetes-common
    - containerd
    - kubernetes-kubeadm
  tasks:
    - import_tasks: ./tasks/gather_facts_masters_workers.yml
    - include_role:
        name: kubernetes-kubeadm
        tasks_from: upgrade
