---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: iperf3
  name: iperf3
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:iperf3
  namespace: cluster-addons
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:privileged
subjects:
- kind: ServiceAccount
  name: iperf3
  namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf3
  labels:
    app: iperf3
spec:
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: iperf3
        #image: r.spiarh.fr/iperf3:latest
        image: docker.io/spiarh/iperf3:latest
        imagePullPolicy: Always
        #command:
        #- tail
        #- "-f"
        #- /dev/null
        args:
        - "-s"
        securityContext:
          runAsUser: 1871
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
      serviceAccountName: iperf3
      terminationGracePeriodSeconds: 0
