---
- name: restart_kubelet
  service:
    name: kubelet
    state: restarted

- name: reload_sysctl
  command: /sbin/sysctl -p --system

- name: restart_systemd_modules_load
  service:
    name: systemd-modules-load
    state: restarted

- name: disable_swap
  command: /sbin/swapoff -a
