---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: ip
  app.kubernetes.io/name: ip
  app.kubernetes.io/managed-by: kustomize

images:
- name: ip
  newName: docker.io/spiarh/ip
  newTag: "0.1"

resources:
- deployment.yaml
- serviceaccount.yaml
- service.yaml
