apiVersion: 1
providers:
- name: 'sidecarProvider'
  orgId: 1
  folder: ''
  type: file
  disableDeletion: false
  allowUiUpdates: false
  options:
    foldersFromFilesStructure: false
    path: /tmp/dashboards
