---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: mariadb
  app.kubernetes.io/name: mariadb
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: ""

images:
- name: mariadb
  newName: docker.io/spiarh/mariadb
  # TODO: add version
  newTag: latest

configMapGenerator:
- name: mariadb-env
  behavior: create
  env: config/env

resources:
- serviceaccount.yaml
- service-headless.yaml
- service.yaml
- statefulset.yaml
