---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-headless
  namespace: prod
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mariadb
      port: 3306
      targetPort: mariadb
