---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 3
  serviceName: mariadb-headless
  updateStrategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: mariadb
          image: mariadb
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: mariadb-env
          - secretRef:
              name: mariadb-env
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - name: mariadb
              containerPort: 3306
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin status -uroot -p${MARIADB_ROOT_PASSWORD}
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin status -uroot -p${MARIADB_ROOT_PASSWORD}
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          securityContext:
            readOnlyRootFilesystem: false
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: mariadb
      serviceAccountName: mariadb
      securityContext:
        fsGroup: 2811
        runAsUser: 2811
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
        storageClassName: my-storage-class
