apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tblshoot
    pod-template-hash: b68d8dc89
  name: tblshoot
  namespace: ops
spec:
  nodeSelector:
    kubernetes.io/hostname: ops-01.caasp.suse.net
  containers:
  - command:
    - tail
    - -f
    - /dev/null
    image: docker.io/spiarh/tblshoot-large:latest
    imagePullPolicy: IfNotPresent
    name: tblshoot
    securityContext:
      allowPrivilegeEscalation: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - name: image-storage
      mountPath: /var/lib/registry
    - name: image-storage-old
      mountPath: /var/lib/registry2-old
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: portus-registry
  serviceAccountName: portus-registry
  terminationGracePeriodSeconds: 0
  volumes:
  - name: image-storage
    persistentVolumeClaim:
      claimName: portus-registry
  - name: image-storage-old
    hostPath:
      path: /data/docker-registry
      type: Directory
