---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/1: runtime/default
    kubernetes.io/psp: suse.caasp.psp.privileged
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  labels:
    run: root
  name: root
  namespace: default
spec:
  containers:
  - command:
    - nsenter
    - --mount=/proc/1/ns/mnt
    - --
    - /bin/bash
    image: docker.io/spiarh/alpine:latest
    imagePullPolicy: Always
    name: "1"
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      privileged: true
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostPID: true
  hostNetwork: true
  #nodeName: worker-0
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 3600
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 3600
