---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: source-ip-app
  name: source-ip-app
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: source-ip-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: source-ip-app
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.4
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        name: echoserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: source-ip-app
  name: source-ip-nodeport
  namespace: default
spec:
  #clusterIP: None
  #externalTrafficPolicy: Local
  externalTrafficPolicy: Cluster
  externalIPs:
  - 10.84.72.147
  ports:
  - nodePort: 31080
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: source-ip-app
  sessionAffinity: None
  type: NodePort
