---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tblshoot
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp.tblshoot.privileged
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'runtime/default'
    apparmor.security.beta.kubernetes.io/allowedProfileName: '*'
    apparmor.security.beta.kubernetes.io/defaultProfileName: 'runtime/default'
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  volumes:
  - '*'
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:tblshoot:privileged
rules:
  - apiGroups: ['extensions']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames: ['psp.tblshoot.privileged']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp:tblshoot:privileged
roleRef:
  kind: ClusterRole
  name: psp:tblshoot:privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: default
  name: tblshoot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tblshoot
  labels:
    app: tblshoot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tblshoot
  template:
    metadata:
      labels:
        app: tblshoot
    spec:
      containers:
      - name: tblshoot
        image: docker.io/spiarh/tblshoot-large:latest
        imagePullPolicy: IfNotPresent
        command:
          - tail
          - -f
          - /dev/null
      securityContext:
        runAsUser: 0
      serviceAccount: tblshoot
      serviceAccountName: tblshoot
      terminationGracePeriodSeconds: 0
