image:
  registry: r.spiarh.fr/library
  name: nginx
  tag: 1.18.0-r1
spec:
  fromImage:
    registry: r.spiarh.fr
    name: alpine
    tag: 3.12.1
  buildArgs:
  - VERSION
  tagFormat: '{{ .VERSION }}'
  facts:
  - name: VERSION
    value: 1.18.0-r1
    source: alpine
    kind: version
  sources:
  - name: alpine
    alpine:
      package: nginx
      repository: main
      versionId: "3.12"
      arch: x86_64
      mirror: http://dl-cdn.alpinelinux.org
