---
- name: install_snap_package
  snap:
    name: lxd
    state: present
    channel: latest/stable

- name: create_lxd_config
  template:
    src: lxd-config-full.yaml.j2
    dest: "{{ lxd_config_path }}"
    owner: root
    group: root
    mode: 0400

- name: configure_lxd
  shell: "/snap/bin/lxd init --preseed < {{ lxd_config_path }}"
  changed_when: false

- name: start_enable_service_lxd
  service:
    name: snap.lxd.daemon.service
    state: started
    enabled: true
