---
#- name: install_packages
#  apt:
#    name: "{{ item.name }}"
#    state: "{{ item.state }}"
#    update_cache: true
#  with_items:
#    - "{{ lxd_pkgs }}"

- name: create_lxd_config
  template:
    src: lxd-config-full.yaml.j2
    dest: "{{ lxd_config_path }}"
    owner: root
    group: root
    mode: 0400

- name: configure_lxd
#  shell: "lxd init --preseed < {{ lxd_config_path }}"
  shell: "/snap/bin/lxd init --preseed < {{ lxd_config_path }}"
  changed_when: false

#- name: start_enable_service_lxd
#  service:
#    name: lxd
#    state: started
#    enabled: true
