---
- set_fact:
    podman:
      apt:
        key: "{{ podman.repo_base }}{{ ansible_facts['lsb']['release'] }}/Release.key"
        repo: "deb {{ podman.repo_base }}{{ ansible_facts['lsb']['release'] }} /"
    cacheable: yes

- name: podman_add_apt_keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "{{ podman.apt.key }}"
    - "{{ kubernetes.apt.key }}"

- name: podman_add_apt_repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "{{ podman.apt.repo }}"
    - "{{ kubernetes.apt.repo }}"

- name: podman_install_packages
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ podman.pkgs }}"
