---
# tasks file for podman
- name: podman_add_apt_keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "{{ podman_apt_keys }}"

- name: podman_add_apt_repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "{{ podman_apt_repos }}"

- name: podman_install_packages
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ podman_pkgs }}"
