---
- name: check_apiserver_is_running
  uri:
     method: GET
     url: https://{{ control_plane_endpoint }}/healthz
     validate_certs: no
     status_code: [200]
  register: apiserver_req
  until: apiserver_req.status == 200
#  failed_when: "'ok' not in apiserver_req.content"
#  failed_when: "'ok' not in apiserver_req.msg"
  failed_when: apiserver_req.status != 200
  retries: 30
  delay: 2

- debug:
    var: apiserver_req.content
