---
- name: copy_join_conf
  template:
    src: join.conf.j2
    dest: "{{ kubeadm_join_file }}"
    owner: root
    group: root
    mode: 0440

- name: run_kubeadm_join
  command: "kubeadm join --config {{ kubeadm_join_file }}  --skip-phases=\"{{ join_skip_phases }}\""
  notify: create_join_witness_file
  register: run_kubeadm_join

- debug: var=run_kubeadm_join.stdout_lines

- meta: flush_handlers

- include_tasks: join_check.yml
  when: run_kubeadm_join is succeeded
