---
- import_tasks: certs.yml
- import_tasks: prereq.yml

- include_tasks: init/copy_conf.yml

- name: run_kubeadm_upgrade
  command: "kubeadm upgrade apply --config {{ kubeadm.init.config_file }} -v{{ kubeadm.log_level }} v{{ kubernetes.version }} --yes"
  register: run_kubeadm_upgrade
  when:
    - inventory_hostname == groups.masters[0]

- name: run_kubeadm_node_upgrade
  command: "kubeadm upgrade node -v{{ kubeadm.log_level }}"
  register: run_kubeadm_node_upgrade

- debug:
    var: run_kubeadm_upgrade

- debug:
    var: run_kubeadm_node_upgrade

- meta: flush_handlers
