---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: docker-registry
  app.kubernetes.io/name: container-registry
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: ""

images:
- name: docker-registry
  newName: docker.io/spiarh/docker-registry
  newTag: "2.7.1"

configMapGenerator:
- name: docker-registry-config
  behavior: replace
  files:
  - config=config/config.yml

resources:
- ./deployment.yaml
- ./serviceaccount.yaml
- ./service.yaml
