---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: http
  - name: debug
    port: 5001
    protocol: TCP
    targetPort: debug
  type: ClusterIP
