from_image:
  name: alpine
  registry: r.spiarh.fr
  tag: 3.12.1
from_image_builder:
  name: golang
  registry: docker.io/library
  tag: 1.15-alpine
image:
  name: stern
  registry: r.spiarh.fr
  tag: 1.13.1
  tag_build:
    type: VERSION
    version: 1.13.1
    version_from:
      owner: stern
      repository: stern
      semver: null
      type: github
      version: null
