---
apiVersion: v1
kind: Pod
metadata:
  name: custom-rpm-repo
  namespace: kube-system
  labels:
    name: custom-rpm-repo
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
spec:
  restartPolicy: Always
  hostNetwork: true
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: "CriticalAddonsOnly"
      operator: "Exists"
  containers:
    - name: custom-rpm-repo
      image: createrepo-nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "250m"
      volumeMounts:
        - name: packages
          mountPath: /srv/www/htdocs
          readOnly: False
  volumes:
    - name: packages
      hostPath:
        path: /root/repos/packages
