---
- name: create_addons_dir
  file:
    path: "{{ addons_directoy }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: copy_addons_manifests
  template:
    src: "{{ item.src }}"
    dest: "{{ addons_directoy }}/{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  register: addons_manifests_copied
  with_items:
    - {src: "psp-rbac-unrestricted.yml", dest: "psp-rbac-unrestricted.yml"}
    - {src: "psp-rbac-relaxed.yml", dest: "psp-rbac-relaxed.yml"}
    - {src: "psp-rbac-restricted.yml", dest: "psp-rbac-restricted.yml"}
    - {src: "psp-rbac-kube-proxy.yml", dest: "psp-rbac-kube-proxy.yml"}
    - {src: "psp-default.yml", dest: "psp-default.yml"}
    - {src: "kubernetes-services-endpoint.yml", dest: "kubernetes-services-endpoint.yml"}
    - {src: "{{ cni.name }}/{{ cni.name }}-{{ vars[cni.name]['version'] }}.yml.j2", dest: "{{ cni.name }}-{{ vars[cni.name]['version'] }}.yml"}
    - {src: "{{ cni.name }}/psp-rbac.yml", dest: "psp-rbac-{{ cni.name }}.yml"}

- name: apply_addons_manifests
  command: "kubectl apply -f {{ addons_directoy }}/{{ item }} --kubeconfig={{ kubeconfig_admin }} -v4"
  with_items:
    - psp-rbac-unrestricted.yml
    - psp-rbac-relaxed.yml
    - psp-rbac-restricted.yml
    - psp-rbac-kube-proxy.yml
    - psp-default.yml
    - kubernetes-services-endpoint.yml
    - "{{ cni.name }}-{{ vars[cni.name]['version'] }}.yml"
    - "psp-rbac-{{ cni.name }}.yml"
  register: addons_manifests_applied

- debug:
    msg: "{{ item.stdout }}"
  with_items:
    - "{{ addons_manifests_applied.results }}"
