---
- name: mount_bpf_fs
  mount:
    path: /sys/fs/bpf
    src: bpffs
    fstype: bpf
    opts: defaults
    state: mounted
  when:
    - cni == "cilium"
    - inventory_hostname not in groups['lxd_k8s_containers']

- name: clean_cni_from_cilium
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/cni/net.d/{{ cilium.cni_conf_name }}"
    - /opt/cni/bin/cilium-cni
    - /var/run/cilium
  when: cni != "cilium"

- name: clean_cni_from_calico
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/cni/net.d/{{ calico.cni_conf_name }}"
    - /etc/cni/net.d/calico-kubeconfig
    - /var/run/calico
    - /var/lib/calico
    - /var/run/nodeagent
    #- /var/lib/cni/networks used by other plugins?
    - /opt/cni/bin/calico
    - /opt/cni/bin/calico-ipam
  when: cni != "calico"

- name: clean_cni_from_flannel
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/cni/net.d/{{ flannel.cni_conf_name }}"
    - /etc/kube-flannel
    - /run/flannel
  when: cni != "flannel"
