- name: install_iscsi_packages
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items:
    - { name: "open-iscsi", state: "present" }

- name: start_enable_service_iscsid
  service:
    name: iscsid
    state: started
    enabled: True
