---
containerd:
  version: 1.3.3
  pkgs:
  - name: containerd=1.3.3-0ubuntu2
    state: present

runtime_endpoint: "/run/containerd/containerd.sock"
image_endpoint: "/run/containerd/containerd.sock"
no_prometheus: "true"
disable_apparmor: "false"
systemd_cgroup: "true"

crictl:
  debug: "false"
  timeout: "8"
