---
# tasks file for kubernetes
- name: add_apt_keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "{{ apt_keys }}"

- name: add_apt_repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "{{ apt_repos }}"

- name: install_packages
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items:
    - "{{ kubernetes_pkgs }}"

- name: add_default_args_kubelet
  template:
    src: default_kubelet.j2
    dest: /etc/default/kubelet
    owner: root
    group: root
    mode: 0644
  when: kubelet_default_args != ""
