---
# tasks file for kubernetes
- import_tasks: swap.yml
  when: kubernetes_common_prereq

- import_tasks: system.yml
  when: kubernetes_common_prereq

- import_tasks: kubernetes.yml
  when: kubernetes_common_install
