kind: Build
image:
  registry: r.spiarh.fr/library
  name: nextcloud
  tag: 20.0.8
spec:
  fromImages:
  - registry: r.spiarh.fr
    name: alpine
    tag: latest
  buildArgs:
  - VERSION
  tagFormat: '{{ .VERSION }}'
  facts:
  - name: VERSION
    value: 20.0.8
    source: github
    kind: version
    semver: < 21.0.0
  sources:
  - name: github
    github:
      owner: nextcloud
      repository: server
      object: tag
